### PR TITLE
Update Altitude Type

### PR DESCRIPTION
**Pull request by brentru**
Updating `SENSOR_TYPE_ALTITUDE` to match https://github.com/adafruit/Adafruit_Sensor/pull/53

### CODE REVIEW

**Comment by brentru** [comment]
Noting that we already have `altitude` defined within WipperSnapper_Components

**Comment by brentru** [comment]
@tyeth  When Loren updates web frontend and MQTT broker, could you test this by updating the BMP280 driver (https://github.com/adafruit/Adafruit_Wippersnapper_Arduino/pull/459/files#diff-fbdee40a3b30c05fec9ab309639e7be55a44cedcbc22ff0aee176c312f7100a0R122) to work with the `altitude` type?

We may need to update a few drivers

**Comment by lorennorman** [comment]
@brentru just checked and we're all good on altitude, it exists in the mqtt broker and the web frontend already. @tyeth is good to go to test things out whenever he's ready!

**Comment by tyeth** [comment]
Made a minor boo-boo, was about to bump version and release, as the latest was weeks old, but it turned out there was a newer release. I've now promoted it to be marked Latest. As a result the version bump in libraries has been done but no changes otherwise, so maybe I leave it there for the next data type addition...

**Comment by brentru** [comment]
@tyeth  Noted, that is ok!

**Pull request merged**
